use_frameworks!

target 'VISPER-Swift_Example' do
  pod 'VISPER-Swift', :path => '../'
  pod 'VISPER-Wireframe', :path => '../../VISPER-Wireframe'
  pod 'VISPER-Wireframe-Core', :path => '../../VISPER-Wireframe'
  pod 'VISPER-Wireframe-UIViewController', :path => '../../VISPER-Wireframe'
  pod 'VISPER-Wireframe-Objc', :path => '../../VISPER-Wireframe'

  target 'VISPER-Swift_Tests' do
    inherit! :search_paths
  end
end
