use_frameworks!

target 'SwiftyVISPER_Example' do
  pod 'SwiftyVISPER', :path => '../'
  pod 'VISPER-Wireframe', :path => '../../VISPER-Wireframe'

  target 'SwiftyVISPER_Tests' do
    inherit! :search_paths

    
  end
end
